### ISSUE TITLE
機能しなくなった

### ISSUE THREAD

**Issue by icesou** [Foo-x/youtube-timestamp-comments#13]
便利に使わせていただいてます
昨日まで正常に使えていたのですが、今日使うと機能しなくなっていました。設定を変えたわけではないので、多分youtubeの仕様変更かと思います。
念の為拡張機能のアンインストール及び再インストールを試してみましたが変わらず。
FIXお願いします

**Comment by icesou** [comment]
FIXありがとうございます!これなしには長時間アーカイブ視聴は考えられません
PS よろしければメールを送ったので見てください

**Comment by icesou** [comment]
youtube君コメント欄の仕様変更しスギィ
再オープンします

**Comment by Foo-x** [comment]
最新のバージョン(0.4.2)で解決するかと思いますので、ご確認いただけると幸いです。

**Comment by icesou** [comment]
迅速なFIXに感謝します
