### ISSUE TITLE
本ツールを愛用しています。検討だけでもしてみてください

### ISSUE THREAD

**Issue by icesou** [Foo-x/youtube-timestamp-comments#20]
このアプリのおかげで長時間のアーカイブも苦もなく見ることができます。ありがとうございます。長く愛用している中で、少し気になるところが見えてきたので書いてもよろしいでしょうか。日々のメンテナンスに比べると取るに足りない要望ですので、イチ利用者の独り言だと思って聴いてください

要望その1
左カラムの時間をダブルクリックすることで直接その時間に飛ぶ機能。
要望の背景
既に長大なタイムスタンプが書き込まれていることに気づかずに、親切心から同じような網羅的なタイムスタンプを書き込んでしまう視聴者が大勢いるとき（複数言語で人気を誇るVTUBERのアーカイブの特徴でもあります）、左カラムの時間をシングルクリックして右のタイムスタンプをスクロールするのが迂遠に感じるます。アーカイブが長時間で、書き込まれるタイムスタンプが多く、そのタイムスタンプが網羅的なほど顕著に感じます。timestamp作成を補助するツールが広がった証でしょうか。嬉しい悲鳴です
例えばこのようなアーカイブです。ホロライブENGLISHの長時間耐久だと複数言語で網羅的と更にエライことになります。
https://www.youtube.com/watch?v=bpOnqpc7xxM

要望その2
左カラムに表示される時間を、書いた人ごとに（せめて網羅的なタイムスタンプを書いてくれる人だけでも）色分けをする機能。
要望の背景
要望その1とほぼ同じですが、網羅的なタイムスタンプが複数あると、時間順にクリックして視聴していこうとするとスクロール量が多く必要とするため。要望その1の実装でほとんど解決します
なんなら現状でも、左カラムのALLで見ればよく、時間順に見ることにこだわらなければ発生しない問題です。ゲーム実況だと時間順に見たいという気になってしまうのです

重ねて申し上げます。イチ利用者のおもいつきですので返信しなくても大丈夫です

**Comment by Foo-x** [comment]
ご要望ありがとうございます！
1つ目はすぐに対応できるかと思いますので、空いている時間に実装します。
2つ目についても良さそうな機能ですね！
ただ、UIを検討しますので、少し時間がかかるかと思います。
よろしくお願いいたします。

**Comment by Foo-x** [comment]
1つ目について対応したバージョン0.5.0の審査が完了し、先ほど配信されました。
2つ目は引き続き対応します。

**Comment by Foo-x** [comment]
2つ目について、色分けによって判別するのは10色以上になると厳しいことが予想されるので断念。
同じタイムスタンプでも人数分だけ別のタブを表示する方向で進めます。

例
以下の2つのコメントがあったとする。

```
# コメント1
1:23 xxx
2:34 yyy

# コメント2
1:23 zzz
```

- before
    - `1:23`と`2:34`の2つのタブを表示し、`1:23`をクリックするとコメント1と2、`2:34`をクリックするとコメント2を表示
- after
    -  `1:23`のタブを2つ、`2:34`のタブを1つ表示し、1つ目の`1:23`か`2:34`をクリックするとコメント1、2つ目の`1:23`をクリックするとコメント2を表示

**Comment by icesou** [comment]
検討していただき、ありがとうございました。
ダブルクリックして即座にジャンプする機能を実装していただけたおかげで、とても楽に長時間のアーカイブを見れます。
この機能についてですが、また一つ思いつきを言って良いでしょうか。素人の発想ですので話半分に聞いてみて下さい
つまり以下の機能です
「ダブルクリックでジャンプしたときに、自動的にタイムスタンプの該当時間の所のところまでスクロールする。単純にCTFL Fの機能を機械的に行い、複雑なタイムスタンプだったり、同時刻の複数のタイムスタンプだった場合は、最終的な微調整は人間が行う。スクロールが難しいなら該当時間の強調表示」

**Comment by Foo-x** [comment]
メモ
> ダブルクリックでジャンプしたときに、自動的にタイムスタンプの該当時間の所のところまでスクロールする。

タイムスタンプを含む要素に `data-value` などの属性を持たせることでCSSセレクタによる検索が可能になるので、`scrollIntoView` などでその位置までスクロールできる。

**Comment by Foo-x** [comment]
こちらのIssueに記載されている機能は、すべてバージョン0.7.0として先ほどストアに公開されましたので、Closeします。
