### ISSUE TITLE
ダークテーマを追加

### ISSUE THREAD

**Issue by icesou** [Foo-x/youtube-timestamp-comments#64]
V0.9.1で今までと同じように本拡張機能のアイコンをクリックすると新しいウィンドウが出現しそこにタイムスタンプが出るようになりました
画像1
![2024-03-31 02_28_33-Window](https://github.com/Foo-x/youtube-timestamp-comments/assets/67061858/7b63fdc5-838d-42ae-bda0-8075abdab847)

対照実験のためバックアップしておいたV0.8.2で同様のことを行ったところはその挙動ではなくきちんと表示された
画像2
![2024-03-31 02_38_47-Window](https://github.com/Foo-x/youtube-timestamp-comments/assets/67061858/db7e7b49-2eeb-43bb-8029-bba5c9e374aa)

ので報告します。環境がVivaldi | 6.6.3271.55 (Stable channel) (64-bit
と特殊なのでこれがこのブラウザ特有の不具合だったらごめんなさい。

**Comment by icesou** [comment]
closeされたスレッドを見落としていました。スクロール位置が保存されない問題に対処するためにウィンドウ化したので仕様だったのですね。今のところウィンドウが出ることで使い勝手が変わったわけではないので特に問題なかったです。
毎日のように愛用している拡張なので驚いたようです。失礼しました
こんな機会でもないと要望を書かないのでついでにと言ってはなんですが、要望を書いてよいでしょうか
出現するウィンドウを黒背景に白文字のダークテーマにできたら最高だなぁ、なんて思っています

**Comment by icesou** [comment]
間違えて返信を頂く前にCLOSEしてしまった。動揺が凄い

**Comment by Foo-x** [comment]
ご報告ありがとうございます！
コメントいただいた通り、スクロール位置の問題に対応するためウィンドウにしました。
副次的に以下の効果もありました。

- ウィンドウのサイズを変更できるようになった
- ウィンドウを開いたまま別のタブを操作できるようになった
- 複数のタブで動画を開いて、それぞれで別のウィンドウを開けるようになった
- 動画を操作するたびに拡張機能のアイコンをクリックする必要がなくなった
    - 今までは動画を操作するとフォーカスが外れてポップアップが閉じていたので、毎回開きなおす必要があった
    - マルチディスプレイで別のディスプレイに置いたり、常に手前に表示したりすると便利

やはり変更履歴のアナウンスがないとわかりにくいですよね...
#41 #65 で対応します。

ダークテーマはたしかに欲しいですね！
このIssueで対応します。

**Comment by icesou** [comment]
ありがたい。楽しみです

**Comment by yoyoyo21** [comment]
お忙しいかと思いますがダークテーマその後いかがでしょうか。私もお待ちしてます！

**Comment by Foo-x** [comment]
対応が完了しました。
https://github.com/Foo-x/youtube-timestamp-comments/compare/v0.9.1...v0.11.0
審査に通り次第公開される予定です。

**Comment by Foo-x** [comment]
公開されたのでこちらはCloseします。
