### ISSUE TITLE
１コメント内に複数のタイムスタンプを書くとその回数分表示される

### ISSUE THREAD

**Issue by dasisyouyu** [Foo-x/youtube-timestamp-comments#7]

**Comment by Foo-x** [comment]
Issue作成ありがとうございます。
こちらは私も課題として認識しており、2つ目以降のタイムスタンプを単純に非表示にするか、より良い方法があるか検討中です。

**Comment by Foo-x** [comment]
新UI案

![image](https://user-images.githubusercontent.com/24248467/97108637-36bae400-1712-11eb-9d94-b18f8fa668b1.png)

- タイムスタンプのリストをソートして左側にまとめ、選択したものだけコメントを表示
- ALLが選択された場合はすべて表示
    - ただし、複数のタイムスタンプを持つコメントは最も早いタイムスタンプの1回分だけ表示

**Comment by icesou** [comment]
良いUIだぁ

**Comment by Foo-x** [comment]
実装が完了したのでクローズします。
ストアへのアップロードも行いましたので、審査が完了次第更新されるかと思います。
![image](https://user-images.githubusercontent.com/24248467/97778633-d4535f00-1bbb-11eb-9546-747a1a601b5b.png)
