### ISSUE TITLE
chrome拡張版の不具合報告

### ISSUE THREAD

**Issue by icesou** [Foo-x/youtube-timestamp-comments#8]
まさに私が求めていた拡張機能です。重宝しています。
不具合報告をします（どこに書くべきか迷ういましたが、こちらであっていますか?）
2020-06-30現在、拡張機能が使えなくなりました
昨日までは正常に使えていました
こちらのライブで確認しました。ttps://www.youtube.com/watch?v=vzarJbwSNbE

当方プログラミングがわからない素人のため流儀がわからないのですが、ついでにこちらに要望も書いてよろしいでしょうか。特にvtuberのライブ配信のタイムスタンプコメントについてです

まえがき
vtuberのライブは、長時間に渡りそして極めて精密にタイムスタンプを書く文化があり、日本語のタイムスタンプの他に英語でのタイムスタンプも大量に投下されます。タイムスタンプ自体が少ないときは、英語だろうとありがたいものですが、人間慣れると欲が出てきてしまいます。
この拡張機能で数段楽になってこれ以上は贅沢な悩みだとツッコミつつ要望いたします
何百件もの英語日本語入り混じったタイムスタンプをクリックするのが大変です。素人なりの考えですので、これらの提案の妥当性自体も検討して下さい。また他の方法でも構いません。実のところ要望1以外は重要じゃないです

要望1
タイムスタンプをクリックし該当シーンを見終わり次のタイムスタンプを見たいとき、あまりにも長大なタイムスタンプを取得している場合、スクロールが大変（贅沢な悩み）です。クリックしたスクロール位置を保持または強調するような機能。
要望2
日本語以外のタイムスタンプの表示優先度を下げる機能。ただしタイムスタンプのみのコメントは表示する機能。

英語のタイムスタンプが入り混じったライブは例えばこんなものがあります
ttps://www.youtube.com/watch?v=9a7_lq72xlk

**Comment by Foo-x** [comment]
報告ありがとうございます！
こちらで問題ありません。

> 2020-06-30現在、拡張機能が使えなくなりました
> 昨日までは正常に使えていました
> こちらのライブで確認しました。ttps://www.youtube.com/watch?v=vzarJbwSNbE

私の環境で確認したところ、下の添付画像のように使用できているようでした。

![image](https://user-images.githubusercontent.com/24248467/86092355-589bb580-bae8-11ea-89f5-feab13f1f0e8.png)

念のため、ページをリロードしてから、改めて確認していただけると幸いです。

> 要望1
> タイムスタンプをクリックし該当シーンを見終わり次のタイムスタンプを見たいとき、あまりにも長大なタイムスタンプを取得している場合、スクロールが大変（贅沢な悩み）です。クリックしたスクロール位置を保持または強調するような機能。

こちらの機能は重要ですね。
下のIssueで対応する予定です。
https://github.com/Foo-x/youtube-timestamp-comments/issues/4

> 要望2
> 日本語以外のタイムスタンプの表示優先度を下げる機能。ただしタイムスタンプのみのコメントは表示する機能。

こちらも確かにあると便利かもしれません。
新しくIssueを作成しましたので、そちらで対応いたします。
ただ、どのように実装するかの検討が必要ですので、多少時間がかかるかと思います。
https://github.com/Foo-x/youtube-timestamp-comments/issues/9

以上、よろしくお願いいたします。

**Comment by icesou** [comment]
返信ありがとうございます。正常に動作するようになったことを報告します

こんなオカルトめいた報告をしたくはないのですが、リロードを行っても改善せず、なぜか拡張機能のアンインストール及びインストールを行ったら正常に動作するようになりました。当初から設定は一切弄っていません。
他に入れているtamperkonkeyスクリプトや拡張機能との競合があるかもしれませんが、再現率は低そうです。当然ublockORIGINはyoutube,comをホワイトリストに指定しています。もしかしてyoutubepremiumであることが影響している・・・?特定できたら再び報告します。

ISSUE建てありがとうございます。要望12に関してはそれぞれのスレッドに描きます。

**Comment by Foo-x** [comment]
情報ありがとうございます。
原因不明ではあるものの、動作はするようになったとのことですので、こちらのIssueはひとまず閉じたいと思います。
また発生した際は気軽にIssueを作成していただければ幸いです。
新機能についてはそれぞれのIssueで対応していきますので、よろしくお願いいたします。

**Comment by icesou** [comment]
ありがとうございます
