### ISSUE TITLE
言語でフィルタ

### ISSUE THREAD

**Issue by Foo-x** [Foo-x/youtube-timestamp-comments#9]
選択した言語のみ表示するようにフィルタする機能の追加。
なお、言語が判定できないコメント(タイムスタンプのみなど)はすべての言語に含める。

**Comment by Foo-x** [comment]
課題: 言語の判定方法

日本語のみかつ、ある程度の精度で良いのであれば、Unicodeでひらがな、カタカナ、漢字のいずれかを含むコメントだけ抽出することで実現できそう。

**Comment by icesou** [comment]
厄介なのがEMO文字だけのタイムスタンプで、こういうのは使えたりするんですよね

**Comment by Foo-x** [comment]
メモ:
下のライブラリが使えそうか調査する。
https://github.com/wooorm/franc

**Comment by Foo-x** [comment]
申し訳ありませんが、こちらの機能を実装することは中止いたします。
この拡張機能で実装するより、専用のツールに任せたほうが精度も保守性も向上するためです。
言語を判定するツールの例: https://detectlanguage.com/

他のツールと連携しやすいように、タイムスタンプを含むコメントのリストを出力する機能は実装するかもしれません。
その際はまたIssueを作成します。

**Comment by icesou** [comment]
本アプリのUI改良によって、日本語だけのタイムスタンプを探すのも難儀しなくなりました。検討していただいてありがとうございます。
